- name: Check if Cilium client is installed on the node
  command: which cilium
  register: cilium_installed
  failed_when: false
  changed_when: false
  when:
    - inventory_hostname in groups['k3sMaster']

- name: Debug cilium_installed.rc
  debug:
    var: cilium_installed.rc
  when:
    - inventory_hostname in groups['k3sMaster']

- name:  Install cilium client
  shell: |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
    CLI_ARCH=amd64
    if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
    sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
    sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
    rm cilium-linux-${CLI_ARCH}.tar.gz*
  when:
    - inventory_hostname in groups['k3sMaster']
    - cilium_installed.rc != 0

