- name: Install K3s master node
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="{{ INSTALL_K3S_EXEC_VARS }}" sh -
  args:
    executable: /bin/bash
  when:
    - inventory_hostname in groups['k3sMaster']
    - "'k3s' not in services"

- name: Get k3s token from master node
  shell: sudo cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token_result
  run_once: true  # Ensures this command only runs once
  when: inventory_hostname in groups['k3sMaster']

- name: Set k3s token as fact
  set_fact:
    k3s_token: "{{ k3s_token_result.stdout }}"
  when: inventory_hostname in groups['k3sMaster']

