---
- name: Write Armbian Image to SD card
  hosts: localhost
  gather_facts: no
  vars:
    compressed_image_path: "{{ lookup('env', 'IMAGE_PATH') }}"
    disk_device: "{{ lookup('env', 'DISK_DEVICE') }}"
    decompressed_image_path: "{{ compressed_image_path | regex_replace('.xz$', '') }}"

  tasks:
    - name: Debug environment variables
      ansible.builtin.debug:
        msg: 
          - "Image path: {{ compressed_image_path }}"
          - "Decompresed Image path: {{ decompressed_image_path }}"
          - "Disk device: {{ disk_device }}"
    - name: Check if compressed image file exists
      ansible.builtin.stat:
        path: "{{ compressed_image_path }}"
      register: compressed_image_file
      failed_when: not compressed_image_file.stat.exists
      become: yes

    - name: Check if disk device exists
      ansible.builtin.stat:
        path: "{{ disk_device }}"
      register: disk_device_exists
      failed_when: not disk_device_exists.stat.exists
      become: yes

    - name: Decompress the image file
      ansible.builtin.command:
        cmd: "xz -d {{ compressed_image_path }}"
        timeout: 600
      when: compressed_image_file.stat.exists and disk_device_exists.stat.exists
      become: yes

    - name: Write decompressed image to disk with dd on macOS ( bs=1m not as linux one 1M)
      ansible.builtin.command:
        cmd: "dd if={{ decompressed_image_path }} of={{ disk_device }} bs=1M status=progress"
        timeout: 600
      register: dd_output
      become: yes
      ignore_errors: yes

    - name: Display dd output
      ansible.builtin.debug:
        var: dd_output.stdout_lines
