---
- name: Resize ext4 Filesystem on /dev/nvme0n1p2
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check the current filesystem size
      command: df -hT /dev/nvme0n1p2
      register: before_resize
      changed_when: false

    - name: Resize ext4 filesystem on /dev/nvme0n1p2
      community.general.filesystem:
        fstype: ext4
        dev: /dev/nvme0n1p2
        resizefs: yes

    - name: Check the filesystem size after resizing
      command: df -hT /dev/nvme0n1p2
      register: after_resize
      changed_when: false

    - name: Display filesystem size before and after resizing
      debug:
        msg:
          - "Before resize: {{ before_resize.stdout_lines }}"
          - "After resize: {{ after_resize.stdout_lines }}"

