---
- name: Configure SSH for Key-Based Authentication
  hosts: all
  become: yes

  tasks:
    - name: Set SSH to key-based authentication only
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart sshd

    - name: Ensure SSH key-based authentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present

    - name: Ensure root login is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

  handlers:
    - name: Restart sshd
      systemd:
        name: sshd
        state: restarted

