---
- name: Gather System Information
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Get system load and uptime
      shell: |
        echo $(uptime | awk -F'load average:' '{ print $2 }' | cut -d, -f1 | tr -d ' ')%\
        $(uptime -p | sed 's/up //')
      register: load_uptime

    - name: Get memory usage
      shell: |
        echo $(free -h | awk '/^Mem:/ {print $3 "/" $2}')
      register: memory_usage

    - name: Get IP address
      shell: |
        hostname -I | cut -d ' ' -f1
      register: ip_address

    - name: Get CPU temperature
      shell: |
        echo $(cat /sys/class/thermal/thermal_zone0/temp | awk '{print $1/1000}')°C
      register: cpu_temp

    - name: Get disk usage of root
      shell: |
        df -h / | awk 'NR==2{print $3 "/" $5}'
      register: disk_usage

    - name: Display system information
      debug:
        msg: |
          System load:   {{ load_uptime.stdout.split()[0] }}\
          Up time:       {{ load_uptime.stdout.split()[1] }} {{ load_uptime.stdout.split()[2] }}
          Memory usage:  {{ memory_usage.stdout }}\
          IP:            {{ ip_address.stdout }}
          CPU temp:      {{ cpu_temp.stdout }}\
          Usage of /:    {{ disk_usage.stdout }}


