---
- name: Install pip3 and pexpect, and Fix GPT on NVMe Drives
  hosts: k3sCluster
  become: yes
  gather_facts: no

  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Ensure pexpect is installed
      ansible.builtin.pip:
        name: pexpect
      become: yes

    - name: Install gdisk
      apt:
        name: gdisk
        state: present

    # - name: Install kpartx
    #   package:
    #     name: kpartx
    #     state: present

    - name: Repair GPT on NVMe Drive
      expect:
        command: gdisk /dev/nvme0n1
        timeout: 60
        echo: yes
        responses:
          (?i)Command \(\? for help\): 'x'
          (?i)Expert command \(\? for help\): 'e'
          (?i)Expert command \(\? for help\): 'w'
          (?i)Do you want to proceed\? \(Y\/N\): 'Y'
      register: gdisk_repair

    - name: Display gdisk output
      debug:
        var: gdisk_repair.stdout_lines

    - name: Run partprobe to inform the kernel of partition changes
      command: partprobe
      ignore_errors: yes

    # - name: Alternatively, run kpartx to update kernel partition mappings
    #   command: kpartx -u /dev/nvme0n1
    #   ignore_errors: yes

    - name: Check if the kernel recognizes the new partition table
      command: fdisk -l /dev/nvme0n1
      register: fdisk_output

    - name: Display fdisk output
      debug:
        var: fdisk_output.stdout_lines
