---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install necessary packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - open-iscsi
      - nfs-common
      - bash
      - curl
      - software-properties-common
      - tmux
      - vim
      - net-tools
    state: present

