---
- name: Read local SSH public key
  ansible.builtin.slurp:
    src: "{{ local_ssh_public_key_path }}"
  register: local_ssh_public_key
  delegate_to: localhost
  run_once: true

- name: Install SSH public key to remote hosts
  ansible.builtin.authorized_key:
    user: "{{ ansible_env.USER }}"
    key: "{{ local_ssh_public_key['content'] | b64decode }}"
    state: present
