apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  blocks:
  - start: "192.168.1.101"
    stop: "192.168.1.20"
  serviceSelector:
    matchExpressions:
      - {key: color, operator: In, values: [blue, cyan]}
